### PR TITLE
fix issue-5: non-idempotence on grub disabling

### LINKED ISSUE #5: disabling in grub is not idempotent
executing the role more than once keep adding new copies of " ipv6.disable=1" to /etc/default/grub

### PR DESCRIPTION
**Pull request by shk3bq4d**
proposal to fix #5

### CODE REVIEW

**Comment by shk3bq4d** [comment]
I still need need to work some more on this

**Comment by shk3bq4d** [comment]
well it now works better to my taste, not perfect on fixing existing repetitions.

sadly a bit too complex

**Comment by juju4** [comment]
Thanks! known issue but not easy to handle unless managing all grub arguments
agreed complex solution

any risk of overlapping variables when used with other roles/playbooks? maybe keep 'ipv6_*' prefix for all of them.

approved github action
- can you check yamllint issues?
- also seems this part of play is not executed even if grub is present in github action image. likely because of ansible_virtualization_type

**Comment by shk3bq4d** [comment]
ok I amended to fix:
* the yaml lint complaint
* prefixing the variables local to the modified task
* 
I did nothing about the code coverage in the github action as the conditions were not modified in the PR (ok, I lack the skill and time to improve that ;-) )

Although it's a progress, I still am not a big fan of my PR as existing lines with the desired substring in the middle of other options will get a modification to move the desired substring at the end. So it idempotency works, but only after two runs.

Slurping the file in a separate task beforehand and conditionally applying the modification would probably be best and it would be possible to produce a simpler version of the regexp as well. I'll see if I eventually produce that.

**Comment by juju4** [comment]
LGTM. Thanks!

**Pull request merged**
